pipeline {
    agent { label 'slave'}

        stages {
            stage ('Test') {
                steps {
                    script{
                        sh ''' 
                            echo "Clonning the repo..."
                            git clone https://github.com/JuanWigg/CI-CD-Project.git
                            cd CI-CD-Project/App
                            echo "Running tests"
                            mvn clean compile test
                            echo "Tests runs succesfully!"
                        '''
                    }              
                }
            }

            stage ('Build') {
                steps {
                    script{
                        
                        sh '''
                            cd CI-CD-Project/App
                            echo "Building the JAR file..."
                            mvn -f pom.xml clean install -Dmaven.test.skip=true
                            echo "JAR file build!"
                        '''
                        
                    }  
                }
            }
  
            stage ('Create and Upload Docker Image') {
                steps {
                    script{
                        sh '''
                            echo "Creating Docker image..."
                        '''
                    }
                    
                }

            }
        }

}